// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.6
// source: protos/options.proto

package protoc_gen_go_http_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpClientFileOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForFile bool `protobuf:"varint,1,opt,name=for_file,json=forFile,proto3" json:"for_file,omitempty"`
}

func (x *HttpClientFileOptions) Reset() {
	*x = HttpClientFileOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpClientFileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpClientFileOptions) ProtoMessage() {}

func (x *HttpClientFileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protos_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpClientFileOptions.ProtoReflect.Descriptor instead.
func (*HttpClientFileOptions) Descriptor() ([]byte, []int) {
	return file_protos_options_proto_rawDescGZIP(), []int{0}
}

func (x *HttpClientFileOptions) GetForFile() bool {
	if x != nil {
		return x.ForFile
	}
	return false
}

type HttpClientFieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default string `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
}

func (x *HttpClientFieldOptions) Reset() {
	*x = HttpClientFieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpClientFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpClientFieldOptions) ProtoMessage() {}

func (x *HttpClientFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protos_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpClientFieldOptions.ProtoReflect.Descriptor instead.
func (*HttpClientFieldOptions) Descriptor() ([]byte, []int) {
	return file_protos_options_proto_rawDescGZIP(), []int{1}
}

func (x *HttpClientFieldOptions) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

type HttpClientMethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *HttpClientMethodOptions) Reset() {
	*x = HttpClientMethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpClientMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpClientMethodOptions) ProtoMessage() {}

func (x *HttpClientMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protos_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpClientMethodOptions.ProtoReflect.Descriptor instead.
func (*HttpClientMethodOptions) Descriptor() ([]byte, []int) {
	return file_protos_options_proto_rawDescGZIP(), []int{2}
}

func (x *HttpClientMethodOptions) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpClientMethodOptions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var file_protos_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*HttpClientFileOptions)(nil),
		Field:         2048,
		Name:          "file_opts",
		Tag:           "bytes,2048,opt,name=file_opts",
		Filename:      "protos/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*HttpClientFieldOptions)(nil),
		Field:         2049,
		Name:          "field_opts",
		Tag:           "bytes,2049,opt,name=field_opts",
		Filename:      "protos/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpClientMethodOptions)(nil),
		Field:         2050,
		Name:          "method_opts",
		Tag:           "bytes,2050,opt,name=method_opts",
		Filename:      "protos/options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional HttpClientFileOptions file_opts = 2048;
	E_FileOpts = &file_protos_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional HttpClientFieldOptions field_opts = 2049;
	E_FieldOpts = &file_protos_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional HttpClientMethodOptions method_opts = 2050;
	E_MethodOpts = &file_protos_options_proto_extTypes[2]
)

var File_protos_options_proto protoreflect.FileDescriptor

var file_protos_options_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x15, 0x48, 0x74, 0x74, 0x70,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x32, 0x0a, 0x16,
	0x48, 0x74, 0x74, 0x70, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x22, 0x45, 0x0a, 0x17, 0x48, 0x74, 0x74, 0x70, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x3a, 0x52, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6f, 0x70, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x80, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x48, 0x74, 0x74, 0x70,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x73, 0x3a, 0x56, 0x0a, 0x0a, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x81, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f,
	0x70, 0x74, 0x73, 0x3a, 0x5a, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x6f, 0x70,
	0x74, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x82, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x48, 0x74, 0x74, 0x70,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x73, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6a,
	0x38, 0x32, 0x35, 0x31, 0x36, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x67, 0x6f, 0x2d, 0x68, 0x74, 0x74, 0x70, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_options_proto_rawDescOnce sync.Once
	file_protos_options_proto_rawDescData = file_protos_options_proto_rawDesc
)

func file_protos_options_proto_rawDescGZIP() []byte {
	file_protos_options_proto_rawDescOnce.Do(func() {
		file_protos_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_options_proto_rawDescData)
	})
	return file_protos_options_proto_rawDescData
}

var file_protos_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_options_proto_goTypes = []interface{}{
	(*HttpClientFileOptions)(nil),      // 0: HttpClientFileOptions
	(*HttpClientFieldOptions)(nil),     // 1: HttpClientFieldOptions
	(*HttpClientMethodOptions)(nil),    // 2: HttpClientMethodOptions
	(*descriptorpb.FileOptions)(nil),   // 3: google.protobuf.FileOptions
	(*descriptorpb.FieldOptions)(nil),  // 4: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil), // 5: google.protobuf.MethodOptions
}
var file_protos_options_proto_depIdxs = []int32{
	3, // 0: file_opts:extendee -> google.protobuf.FileOptions
	4, // 1: field_opts:extendee -> google.protobuf.FieldOptions
	5, // 2: method_opts:extendee -> google.protobuf.MethodOptions
	0, // 3: file_opts:type_name -> HttpClientFileOptions
	1, // 4: field_opts:type_name -> HttpClientFieldOptions
	2, // 5: method_opts:type_name -> HttpClientMethodOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_options_proto_init() }
func file_protos_options_proto_init() {
	if File_protos_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpClientFileOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpClientFieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpClientMethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_protos_options_proto_goTypes,
		DependencyIndexes: file_protos_options_proto_depIdxs,
		MessageInfos:      file_protos_options_proto_msgTypes,
		ExtensionInfos:    file_protos_options_proto_extTypes,
	}.Build()
	File_protos_options_proto = out.File
	file_protos_options_proto_rawDesc = nil
	file_protos_options_proto_goTypes = nil
	file_protos_options_proto_depIdxs = nil
}
