// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Your base urlapi.com

package example

import (
	json "encoding/json"
	log "log"
	http "net/http"
)

func GetUser() {
	res, err := http.Get("https://api.com/user")

	target := User{}
	if err != nil {
		log.Fatal(err)
	}
	defer res.Body.Close()
	json.NewDecoder(res.Body).Decode(target)
}
