// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Your base urlapi.com

package example

import (
	log "log"
	http "net/http"
)

func main() {
	res, err := http.Get("api.com")

	if err != nil {
		log.Fatal(err)
	}
	defer res.Body.Close()

}
